### PR TITLE
Discards the ActiveJob::DeserializationError error fixes #413

### LINKED ISSUE #369: Cleanup AnnotationResources that no longer have associated Annotot::Annotations
It seems like there is an issue with AnnotationResources that try and get reindexed that may have not been cleaned up when an Annotot::Annotation was destroyed.

Reported via email by Riccardo.

What can we do here? A rake task that cleans this up? Better link the AnnotationResource and Annotot::Annotations?

### LINKED ISSUE #413: skip failed indexing jobs based off of Annotation not being found.

### PR DESCRIPTION
**Pull request by mejackreed**
Related to https://app.honeybadger.io/projects/55864/faults/49377921

The BAV team is noticing this error continually happens for annotations that may have been deleted, but perhaps their references in `AnnotationResources` were not cleaned up.

Potentially also fixes #369

### CODE REVIEW

File: spec/jobs/index_annotation_job_spec.rb [hunk 1]
```diff
@@ -35,6 +36,22 @@
...
+
+      before do
+        annotation.delete
+        allow(AnnotationResource).to receive(:new).with(exhibit: nil,
+                                                        annotations: [annotation.to_global_id]).and_return(stub_resource)
+      end
+
+      it 'discards the job' do
+        perform_enqueued_jobs do
+          described_class.perform_later(annotation)
```
Comment (jkeck) [inline spec/jobs/index_annotation_job_spec.rb]: Is there an assertion happening here?

Comment (mejackreed) [reply spec/jobs/index_annotation_job_spec.rb]: So its a failing test without the change, I guess I can explicitly assert does not raise?

Comment (mejackreed) [reply spec/jobs/index_annotation_job_spec.rb]: I've pushed up the assertion. Nice catch!
