### PR TITLE
parse the annotation data, as it is stored as a JSON string

### LINKED ISSUE #169: Investigate annotation indexing on stage env
Annotation indexing is throwing some errors when trying in our stage env:

```
2018-06-29T14:44:50.431Z 9550 TID-1217f2 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"IndexAnnotationJob","queue":"default","args":[{"job_class":"IndexAnnotationJob","job_id":"d594964d-48cf-42b2-88a0-d39af64a586a","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://vatican-exhibits/Annotot::Annotation/2061"}],"executions":0,"locale":"en"}],"retry":true,"jid":"46283a4fa55004d6bbfc7ff9","created_at":1530283490.4263225,"enqueued_at":1530283490.426587},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"IndexAnnotationJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"IndexAnnotationJob\",\"job_id\":\"d594964d-48cf-42b2-88a0-d39af64a586a\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://vatican-exhibits/Annotot::Annotation/2061\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"46283a4fa55004d6bbfc7ff9\",\"created_at\":1530283490.4263225,\"enqueued_at\":1530283490.426587}"}
2018-06-29T14:44:50.431Z 9550 TID-1217f2 WARN: NoMethodError: undefined method `[]' for nil:NilClass
2018-06-29T14:44:50.431Z 9550 TID-1217f2 WARN: /srv/app/releases/20180629141801/app/jobs/index_annotation_job.rb:14:in `index'
/srv/app/releases/20180629141801/app/jobs/index_annotation_job.rb:7:in `perform'
```

### PR DESCRIPTION
**Pull request by mejackreed**
Fixes #169

### CODE REVIEW

File: app/jobs/index_annotation_job.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ def perform(annotation)
   private
 
   def index(annotation)
-    manifest_uri = annotation.data['on'].first['within']['@id']
+    manifest_uri = JSON.parse(annotation.data)['on'].first['within']['@id']
```
Comment (cbeer) [inline app/jobs/index_annotation_job.rb]: I find something suspect about all this. Annotot says it is serializing and deserializing the `data` attribute for us:

https://github.com/mejackreed/annotot/blob/master/app/models/annotot/annotation.rb#L6

Is it possible we're just storing strings instead of actual structured data?

Comment (mejackreed) [reply app/jobs/index_annotation_job.rb]: Perhaps it is? https://github.com/mejackreed/annotot/blob/master/app/controllers/annotot/annotations_controller.rb#L19
